name: TpoToggle
version: 1.0
main: com.TpoToggle.TpoToggle
author: YourName
commands:
  tpotoggle:
    description: Toggle teleport protection on or off.
    usage: /tpotoggle
    permission: tpotoggle.use
    permission-message: You do not have permission to use this command.
permissions:
  tpotoggle.use:
    description: Allows the player to toggle teleport protection.
    default: true
  tpotoggle.bypass:
    description: Allows the player to bypass teleport protection.
    default: false  # Admins and other players can't bypass TPO unless explicitly given this permission.
